local F = require('utils.functions')

F.vg('vim_markdown_no_default_keymappings', '1')
F.vg('vim_markdown_no_extensions_in_markdown', '1')
F.vg('vim_markdown_edit_url_in', 'vspilt')
F.vg('vim_markdown_toc_autofit', '1')
F.vg('vim_markdown_folding_disabled', '1')
F.vg('vim_markdown_folding_level', '6')
F.vg('vim_markdown_new_list_item_indent', '0')
F.vg('vim_markdown_emphasis_multiline', '0')
F.vg('vim_markdown_strikethrough', '1')
F.vg('vim_markdown_math', '1')
F.vg('vim_markdown_conceal_code_blocks', '0')
F.vg('tex_conceal', '')
F.vg('vim_markdown_frontmatter', '1')
F.vg('vim_markdown_toml_frontmatter', '1')
F.vg('vim_markdown_json_frontmatter', '1')
