#!/bin/sh
#  ____   ____
#  |   \  |  |______
#  |    \ |  | ___  \
#  |     \|  | |  \  |
#  |  \   \  | |__/  |
#  |  |\     | _____/
#  |__| \____| | Author: Nico Pareigis
#           |__| bspwm

# CONFIGURATION
if [ $MACHINE = 'DT' ]; then
  bspc monitor DP-2 -d 1 2 3 4
  bspc monitor DP-0 -d 5
else
  bspc monitor eDP1 -d 1 2 3 4
fi

bspc config window_gap      18
bspc config border_width    2
bspc config split_ratio     0.50
bspc config top_padding     0
bspc config right_padding   0
bspc config bottom_padding  0
bspc config left_padding    0

# normal_border_color   unfocused window
# focused_border_color  active window; focused monitor
# presel_feedback_color preselect preview

if [ $MACHINE = 'DT' ]; then
  # cthulu
  #   bspc config focused_border_color  '#6090a0'
  #   bspc config active_border_color   '#205060'
  #   bspc config normal_border_color   '#205060'
  #   bspc config presel_feedback_color '#104050'
  # sakura
  #   bspc config focused_border_color  '#703040'
  #   bspc config active_border_color   '#242424'
  #   bspc config normal_border_color   '#242424'
  #   bspc config presel_feedback_color '#181818'
  # flower
  #   bspc config focused_border_color  '#ffbf21'
  #   bspc config active_border_color   '#3a7271'
  #   bspc config normal_border_color   '#3a7271'
  #   bspc config presel_feedback_color '#3a7271'
  # aenami
  #   bspc config focused_border_color  '#fa486a'
  #   bspc config active_border_color   '#20323e'
  #   bspc config normal_border_color   '#20323e'
  #   bspc config presel_feedback_color '#fa486a'
  # saturn
    bspc config focused_border_color  '#ffffff'
    bspc config active_border_color   '#212121'
    bspc config normal_border_color   '#212121'
    bspc config presel_feedback_color '#fafafa'
  Wallpaper=~/Pictures/Wallpapers/monochrome/saturn.png
else
  # cubes
    bspc config normal_border_color   '#303030'
    bspc config focused_border_color  '#e8e8e8'
    bspc config presel_feedback_color '#e8e8e8'
    Wallpaper=~/Pictures/Wallpapers/monochrome/cubes.png
fi

bspc config single_monocle          true
bspc config pointer_modifier        super
bspc config pointer_action1         move
bspc config pointer_action2         none
bspc config pointer_action3         resize_corner
bspc config click_to_focus          button1
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor false

bspc rule -r "*"
bspc rule -a discord  desktop='^5' follow=off
bspc rule -a Steam    desktop='^4' follow=off     state=floating
bspc rule -a *:*:'GNU Image Manipulation Program' state=floating
bspc rule -a *:*:Picture-in-Picture               state=floating

# AUTOSTART
if [ $MACHINE = 'DT' ]; then
  dunst &
  pgrep sxhkd || sxhkd ~/.config/sxhkd/sxhkdrc.dt &
  pgrep conky || { conky -c ~/.config/conky/conky.conf; \
      conky -c ~/.config/conky/clock.conf; bspc monitor -f primary; } &
else
  dunst -conf ~/.config/dunst/dunstrc.lt &
  pgrep sxhkd || sxhkd ~/.config/sxhkd/sxhkdrc.lt &
fi
picom --experimental-backends --unredir-if-possible &
feh --no-fehbg --bg-fill $Wallpaper &

# SCRATCHPADS
bspc rule -a *:*:sFiles hidden=on sticky=on locked=on state=floating rectangle=1280x720+320+180
bspc rule -a *:*:sMusic hidden=on sticky=on locked=on state=floating rectangle=1280x720+320+180
bspc rule -a *:*:sCalc  hidden=on sticky=on locked=on state=floating rectangle=300x400+50+50

# FLOAT windows on desktop '^4'
TargetDeskId=$(bspc query -D -d '^4')
bspc subscribe node_add | while read NodeInfo; do
  DeskId=${NodeInfo#node_add 0x* }
  DeskId=${DeskId%% *}
  NodeId=${NodeInfo##* }
  [ $TargetDeskId = $DeskId ] && bspc node $NodeId -t floating
done

if [ $MACHINE = 'DT' ]; then
  sleep 2
  noisetorch -i \
    -s alsa_input.usb-Generic_Blue_Microphones_201701110001-00.analog-stereo \
    -t 95 &
fi
