#!/bin/sh
#  ____   ____
#  |   \  |  |______
#  |    \ |  | ___  \
#  |     \|  | |  \  |
#  |  \   \  | |__/  |
#  |  |\     | _____/
#  |__| \____| | Author: Nico Pareigis
#           |__| bspwm
# SETUP
bscp monitor -r any
bspc desktop -r any
bspc rule -r *


# CONFIG
if [ $MACHINE = 'DT' ]; then
  bspc monitor DP-2 -d 1 2 3 4
  bspc monitor DP-0 -d 5
  bspc config pointer_motion_interval 7
else
  bspc monitor eDP1 -d 1 2 3 4
  bspc config pointer_motion_interval 16
fi

bspc config window_gap      18
bspc config border_width    0
bspc config split_ratio     0.50
bspc config top_padding     0
bspc config right_padding   0
bspc config bottom_padding  0
bspc config left_padding    0

Piconf=$XDG_CONFIG_HOME/picom/picom.conf
Theme='forest'
if [ $Theme = 'forest' ]; then
  bspc config focused_border_color  '#a7c080'
  bspc config active_border_color   '#323d43'
  bspc config normal_border_color   '#323d43'
  bspc config presel_feedback_color '#a7c080'
  Wallpaper=$HOME/Media/Pictures/Wallpapers/everforest_blank.png
  Piconf=$Piconf.min
elif [ $Theme = 'sakura' ]; then
  bspc config focused_border_color  '#2d3740'
  bspc config active_border_color   '#08171e'
  bspc config normal_border_color   '#08171e'
  bspc config presel_feedback_color '#0d1720'
  Wallpaper=$HOME/Media/Pictures/Wallpapers/nature/white_sakura.jpg
fi

bspc config single_monocle          true
bspc config pointer_modifier        super
bspc config pointer_action1         move
bspc config pointer_action2         none
bspc config pointer_action3         resize_corner
bspc config click_to_focus          button1
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor false


# RULES
bspc rule -a discord  desktop='^5' follow=off state=floating
bspc rule -a Spotify  desktop='^5' follow=off state=floating
bspc rule -a Steam    desktop='^4' follow=off state=floating
bspc rule -a ftb-app  desktop='^4' follow=off state=floating
bspc rule -a Gimp                             state=floating
bspc rule -a *:*:Picture-in-Picture           state=floating


# AUTOSTART
if [ $MACHINE = 'DT' ]; then
  pgrep dunst || dunst &
  pgrep sxhkd || \
    sxhkd $XDG_CONFIG_HOME/sxhkd/sxhkdrc.dt $XDG_CONFIG_HOME/bspwm/sxhkdrc.bspwm &
  pgrep polybar || polybar DT -r &
  pgrep conky   || { conky -c $XDG_CONFIG_HOME/conky/system.conf; \
      conky -c $XDG_CONFIG_HOME/conky/time.conf; bspc monitor -f primary; } &
  pgrep ssm || ssm -t 60 -e b -c 75 -g 75 &
else
  dunst -conf $XDG_CONFIG_HOME/dunst/dunstrc.lt &
  pgrep sxhkd || \
    sxhkd $XDG_CONFIG_HOME/sxhkd/sxhkdrc.lt $XDG_CONFIG_HOME/bspwm/sxhkdrc.bspwm &
  pgrep ssm || ssm -t 60 -e g -b 30 -c 70 &
fi
picom --config $Piconf &
feh --no-fehbg --bg-fill $Wallpaper &


# FLOAT windows on desktop '^4' and force Steam games to desktop '^4'
TargetDeskId=`bspc query -D -d '^4'`
bspc subscribe node_add | while read REPLY; do
  DeskId=${REPLY#node_add 0x* }; DeskId=${DeskId%% *}
  NodeId=${REPLY##* }

  `xprop -id $NodeId | grep 'STEAM_GAME(CARDINAL)'` && bspc node $NodeId -d '^4'
  [ $TargetDeskId = $DeskId ] && bspc node $NodeId -t floating
done
