#!/bin/sh
#  ____   ____
#  |   \  |  |______
#  |    \ |  | ___  \
#  |     \|  | |  \  |
#  |  \   \  | |__/  |
#  |  |\     | _____/
#  |__| \____| | Author: Nico Pareigis
#           |__| bspwm

# CONFIGURATION
bspc monitor DP-2 -d 1 2 3 4
bspc monitor DP-0 -d 5

bspc config window_gap      12
bspc config border_width    2
bspc config split_ratio     0.50
bspc config top_padding     0
bspc config right_padding   0
bspc config bottom_padding  0
bspc config left_padding    0

# bspc config focused_border_color  '#6090a0'
# bspc config active_border_color   '#205060'
# bspc config normal_border_color   '#205060'
# bspc config presel_feedback_color '#104050'

# bspc config focused_border_color  '#703040'
# bspc config active_border_color   '#242424'
# bspc config normal_border_color   '#242424'
# bspc config presel_feedback_color '#181818'

# bspc config focused_border_color  '#ffbf21'
# bspc config active_border_color   '#3a7271'
# bspc config normal_border_color   '#3a7271'
# bspc config presel_feedback_color '#3a7271'

bspc config focused_border_color  '#fa486a'
bspc config active_border_color   '#20323e'
bspc config normal_border_color   '#20323e'
bspc config presel_feedback_color '#fa486a'

bspc config single_monocle          true
bspc config pointer_modifier        shift
bspc config pointer_action1         move
bspc config pointer_action2         none
bspc config pointer_action3         resize_corner
bspc config click_to_focus          button1
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor false

bspc rule -r "*"
bspc rule -a discord  desktop='5' follow=off
bspc rule -a Gimp                            state=floating
bspc rule -a Steam    desktop='4' follow=off state=floating

# AUTOSTART
dunst &
pgrep sxhkd || sxhkd &
picom --experimental-backends --unredir-if-possible &
feh --no-fehbg --bg-fill ~/Pictures/alena_aenami/aa_02.jpg &
pgrep conky || { conky -c ~/.config/conky/conky.conf; \
  conky -c ~/.config/conky/clock.conf; bspc monitor -f primary; } &

# SCRATCHPADS
bspc rule -a *:*:sFiles hidden=on sticky=on locked=on state=floating rectangle=1280x720+320+180
bspc rule -a *:*:sMusic hidden=on sticky=on locked=on state=floating rectangle=1280x720+320+180
bspc rule -a *:*:sCalc  hidden=on sticky=on locked=on state=floating rectangle=300x400+50+50
bspc rule -a *:*:Picture-in-Picture state=floating

[ $(ps -x | rg sFiles | wc -l) -eq 1 ] \
  && alacritty -t sFiles -e ranger &
[ $(ps -x | rg sMusic | wc -l) -eq 1 ] \
  && alacritty -t sMusic -e ~/.cargo/bin/spotify_player &
[ $(ps -x | rg sCalc  | wc -l) -eq 1 ] \
  && alacritty -t sCalc -e bc -q &

