#!/bin/sh
# Dependencies: alacritty, bspc (duh), grep, tr, wmctrl
# Scratchpads should be hidden, sticky, and floating

Name=$1
case $Name in
  sFiles) Program="ranger $HOME"; break;;
  sMusic) Program="$HOME/.cargo/bin/spotify_player"; break;;
  sCalc)  Program='bc -ql'; break;;
  *)      exit 1;;
esac

# visible scratchpad (if any)
Visible=$(bspc query -N -n .\!hidden.sticky.floating | tr [:upper:] [:lower:])

# target scratchpad window id
TargetWid="$(wmctrl -l | grep $Name)"

# run scratchpad if not running; sleep required because wmctrl is slow
[ -z "$TargetWid" ] && { (alacritty -t $Name -e $Program &); sleep 0.3; \
                          TargetWid="$(wmctrl -l | grep $Name)"; }

TargetWid=${TargetWid%% *}

# toggle visible if it's not the target (-> no overlapping scratchpads)
[ -n "$Visible" ] && [ $Visible != $TargetWid ] \
  && bspc node $Visible -g hidden -f

# toggle target scratchpad. Parameter expansion to prevent unwanted window
# toggling with potential script errors
bspc node ${TargetWid:-0} -g hidden -d focused -f

