#!/bin/bash
#  ____   ____
#  |   \  |  |______
#  |    \ |  | ___  \
#  |     \|  | |  \  |
#  |  \   \  | |__/  |
#  |  |\     | _____/
#  |__| \____| | Author: Nico Pareigis
#           |__| bspwm

bspc desktop any -r
bspc rule -r *


# CONFIG
if [[ $MACHINE == DT ]]; then
  bspc monitor DP-2 -d 1 2 3 4
  bspc monitor DP-0 -d 5
  bspc config pointer_motion_interval 7
else
  bspc monitor eDP1 -d 1 2 3 4
  bspc config pointer_motion_interval 16
fi

bspc config window_gap      18
bspc config border_width    2
bspc config split_ratio     0.50
bspc config top_padding     0
bspc config right_padding   0
bspc config bottom_padding  0
bspc config left_padding    0

bspc config single_monocle          false
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         none
bspc config pointer_action3         resize_corner
bspc config click_to_focus          button1
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor false

bspc config focused_border_color  '#a7c080'
bspc config active_border_color   '#323d43'
bspc config normal_border_color   '#323d43'
bspc config presel_feedback_color '#a7c080'


# RULES
bspc rule -a discord  desktop='^5' follow=off state=floating
bspc rule -a Spotify  desktop='^5' follow=off state=floating
bspc rule -a steam    desktop='^4' follow=off state=floating
bspc rule -a ftb-app  desktop='^4' follow=off state=floating
bspc rule -a Gimp                             state=floating
bspc rule -a *:*:Picture-in-Picture           state=floating


# AUTOSTART
pgrep eww || eww daemon &
eww open bar-${MACHINE,,} &

if [[ $MACHINE == DT ]]; then
  pgrep dunst || dunst &
  pgrep sxhkd || sxhkd "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc.dt "$XDG_CONFIG_HOME"/bspwm/sxhkdrc.bspwm &
  pgrep conky || { \
    conky -c "$XDG_CONFIG_HOME"/conky/system.lua; \
    conky -c "$XDG_CONFIG_HOME"/conky/time.lua; \
    bspc monitor -f primary; \
  } &
  pgrep ssm || ssm -t 60 -e b -c 80 -g 80 &
else
  pgrep dunst || dunst -conf "$XDG_CONFIG_HOME"/dunst/dunstrc.lt &
  pgrep sxhkd || sxhkd "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc.lt "$XDG_CONFIG_HOME"/bspwm/sxhkdrc.bspwm &
  pgrep ssm || ssm -t 60 -e g -b 30 -c 70 &
fi

[[ -f $WALLPAPER ]] && feh --no-fehbg --bg-fill "$WALLPAPER"
"$XDG_CONFIG_HOME"/bspwm/scripts/gulp &


# float desktop '^4'; force steam to desktop '^4'
typeset target_id=`bspc query -D -d '^4'`
while read -a REPLY; do
  typeset node_id=${REPLY[-1]} desk_id=${REPLY[-3]}

  `xprop -id $node_id | grep 'STEAM_GAME(CARDINAL)' 2>/dev/null` && bspc node $node_id -d '^4'
  [[ $target_id == $desk_id ]] && bspc node $node_id -t floating
done < <(bspc subscribe node_add) &

# hide bar on fullscreen apps
while read -a REPLY; do
  [[ ${REPLY[-2]} != fullscreen ]] && continue

  if [[ ${REPLY[-1]} == on ]]; then
    eww close bar-${MACHINE,,}
  else
    eww open bar-${MACHINE,,}
  fi
done < <(bspc subscribe node_state) &
