#!/bin/bash
# (Un-)Hides all windows but the focused one. Acts like a toggle for the builtin
# monocle layout, but prevents other windows from showing behind the focused
# one, as is the case when using transparency.
# The windows to (un-)hide are, as of now, expected to be non-sticky (in order
# to not affect scratchpads), and tiled.

Active=$(bspc query -N -n .focused)

readarray -t Nodes < <(bspc query -N -n .\!hidden.\!sticky.tiled -d .focused)
(( ${#Nodes[@]} > 1 )) && Hide=1 || Hide=0

if (( $Hide == 1 )); then
  for Node in ${Nodes[@]}; do
    [[ $Node == $Active ]] && continue
    bspc node $Node -g hidden=on
  done
fi

if (( $Hide == 0 )); then
  readarray -t Nodes < <(bspc query -N -n .hidden.\!sticky.tiled -d .focused)
  for Node in ${Nodes[@]}; do
    bspc node $Node -g hidden=off
  done
fi

