#!/usr/bin/bash

if [[ $ROFI_RETV =~ 1|2 ]]; then
  if ! command -v $@ >/dev/null; then
    printf "not available - %s\n" $@ >&2
    exit 1
  fi
  coproc ( "$@" >/dev/null 2>&1 )
  exit 0
fi

while read; do
  printf "%s\n" $REPLY
done < ${0%/*}/rofi-custom-items
