general {
    lock_cmd = pgrep hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && openrgb -p off
    inhibit_sleep = 0
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 1200
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 7200
    on-timeout = systemctl suspend
}
