#!/bin/sh
Wallpaper=~/Pictures/Wallpapers/destiny/worm_god.jpg

dunst &
pgrep sxhkd || sxhkd ~/.config/worm/sxhkdrc.worm &
picom --experimental-backends --unredir-if-possible &
feh --no-fehbg --bg-fill $Wallpaper


wormc text-font 'Azeret Mono':size=9
wormc frame-left T
wormc frame-right M, C

wormc gaps    24
wormc struts  24 24 24 24
wormc layout  floating
wormc border-width  0
wormc border-active-pixel   '#813132'
wormc border-inactive-pixel '#4c2021'


sleep 2 && noisetorch -i -s \
  alsa_input.usb-Generic_Blue_Microphones_201701110001-00.analog-stereo -t 95 &
